(function(){
const API='https://poxuyzcaejbqouelzwob.supabase.co/functions/v1/guest-reservations';
let remoteReservations=[];
function refs(){try{return JSON.parse(localStorage.getItem('sushiClubRemoteRefs')||'[]')}catch(e){return[]}}
function saveRefs(v){localStorage.setItem('sushiClubRemoteRefs',JSON.stringify(v.slice(0,20)))}
function addRef(code,token){const a=refs().filter(x=>x.code!==code);a.unshift({code,token});saveRefs(a)}
async function apiGet(params){const u=new URL(API);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));const r=await fetch(u);const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j.error||'Request failed'),{code:j.error,status:r.status,data:j});return j}
async function apiPost(body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(j.error||'Request failed'),{code:j.error,status:r.status,data:j});return j}
function errText(e){if(e&&e.code==='unavailable')return msg('unavailable');if(e&&e.code==='duplicate')return msg('duplicate');return 'Something went wrong. Please try again.'}
async function refreshRemoteMyReservations(){const out=[];for(const x of refs()){try{const j=await apiGet({action:'get',code:x.code,token:x.token});if(j.reservation){j.reservation._token=x.token;out.push(j.reservation)}}catch(e){}}remoteReservations=out;renderMyReservations();refreshMyHome();}
window.myReservations=function(){return remoteReservations.slice().sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))};
window.rememberMyReservation=function(){};
window.renderGuestTimes=async function(){const date=document.getElementById('rdate').value||today();const party=Number(document.getElementById('guests').value||1);let slots=[];try{slots=(await apiGet({action:'availability',date,party})).slots||[]}catch(e){}let first=null;document.querySelectorAll('#reserveTimes .time').forEach(b=>{const s=slots.find(x=>x.time===b.innerText);const unavailable=s?!s.available:false;b.disabled=unavailable;b.style.opacity=unavailable?'.35':'1';b.style.cursor=unavailable?'not-allowed':'pointer';if(unavailable)b.classList.remove('active');if(!unavailable&&!first)first=b});if(!document.querySelector('#reserveTimes .time.active')&&first)first.classList.add('active');syncSelectedTime()};
window.confirmReservation=async function(){const rules=document.getElementById('v13RulesAck');if(!rules||!rules.checked)return alert(msg('agreePolicy'));const name=document.getElementById('rname').value.trim(),date=document.getElementById('rdate').value,guests=Number(document.getElementById('guests').value),active=document.querySelector('#reserveTimes .time.active:not(:disabled)');const room=guestType==='hotel'?document.getElementById('rroom').value.trim():'';const hotelContact=document.getElementById('hotelContact').value.trim(),outsidePhone=document.getElementById('outsidePhone').value.trim(),outsideEmail=document.getElementById('outsideEmail').value.trim();const email=guestType==='outside'?outsideEmail:'',contact=guestType==='hotel'?hotelContact:outsidePhone,request=document.getElementById('rrequest').value.trim();if(!name||!date||!guests||guests<1||!active)return alert(msg('mainRequired'));if(guestType==='hotel'&&!room)return alert(msg('enterRoom'));if(guestType==='outside'&&!outsidePhone&&!outsideEmail)return alert(msg('enterOutsideContact'));try{const j=await apiPost({action:'create',name,date,time:active.innerText,guests,guestType,room,contact,email,request,rulesVersion:'1.0'});addRef(j.reservation.requestId,j.manageToken);j.reservation._token=j.manageToken;remoteReservations.unshift(j.reservation);refreshMyHome();document.getElementById('successTitle').innerText=msg('sentTitle');document.getElementById('successText').innerText=msg('sentText');const r=j.reservation;document.getElementById('summary').innerHTML='<b>'+escapeHtml(msg('request'))+' '+escapeHtml(r.requestId)+'</b><br><br><b>'+escapeHtml(msg('leadGuest'))+':</b> '+escapeHtml(r.name)+'<br><b>'+escapeHtml(msg('dateTime'))+':</b> '+r.date+' · '+r.time+'<br><b>'+escapeHtml(msg('partySize'))+':</b> '+r.guests+' '+escapeHtml(guestWord(r.guests))+(r.room?'<br><b>'+escapeHtml(msg('room'))+':</b> '+escapeHtml(r.room):'');show('success')}catch(e){alert(errText(e));await renderGuestTimes()}};
window.cancelMyReservation=async function(id){const r=remoteReservations.find(x=>Number(x.id)===Number(id));if(!r||!isManageable(r))return alert(msg('cannotCancel'));if(!confirm(msg('confirmCancel')))return;try{const x=refs().find(z=>z.code===r.requestId);await apiPost({action:'cancel',code:r.requestId,token:x&&x.token});await refreshRemoteMyReservations();await renderGuestTimes()}catch(e){alert(errText(e))}};
window.editMyReservation=function(id){const r=remoteReservations.find(x=>Number(x.id)===Number(id));if(!r||!isManageable(r))return alert(msg('cannotEdit'));guestEditingId=Number(id);document.getElementById('guestEditRef').textContent=(r.requestId||msg('reservation'))+' · '+msg('currentStatus')+': '+statusText(r.status);document.getElementById('geDate').value=r.date||today();document.getElementById('geDate').min=today();document.getElementById('geTime').innerHTML=TIMES.map(t=>'<option value="'+t+'" '+(t===r.time?'selected':'')+'>'+t+'</option>').join('');document.getElementById('geGuests').value=r.guests||1;document.getElementById('geName').value=r.name||'';document.getElementById('geRoom').value=r.room||'';document.getElementById('gePhone').value=r.contact||'';document.getElementById('geEmail').value=r.email||'';document.getElementById('geRequest').value=r.request||'';document.getElementById('guestEditOverlay').style.display='flex'};
window.saveGuestEdit=async function(){const r=remoteReservations.find(x=>Number(x.id)===Number(guestEditingId));if(!r)return;const body={action:'update',code:r.requestId,token:(refs().find(z=>z.code===r.requestId)||{}).token,date:document.getElementById('geDate').value,time:document.getElementById('geTime').value,guests:Number(document.getElementById('geGuests').value),name:document.getElementById('geName').value.trim(),room:document.getElementById('geRoom').value.trim(),contact:document.getElementById('gePhone').value.trim(),email:document.getElementById('geEmail').value.trim(),request:document.getElementById('geRequest').value.trim()};try{await apiPost(body);closeGuestEdit();await refreshRemoteMyReservations();await renderGuestTimes();alert(msg('editUpdated'))}catch(e){alert(errText(e))}};
window.findReservation=async function(){const ref=document.getElementById('findRef').value.trim().toUpperCase(),identity=document.getElementById('findIdentity').value.trim(),result=document.getElementById('findResult');try{const j=await apiPost({action:'claim',code:ref,identity});addRef(ref,j.manageToken);j.reservation._token=j.manageToken;await refreshRemoteMyReservations();result.innerHTML=bookingCard(j.reservation,true);refreshMyHome()}catch(e){result.innerHTML='<div class="smallnote">'+escapeHtml(e.code==='identity_mismatch'?msg('detailsMismatch'):msg('notFound'))+'</div>'}};

async function handleReservationDeepLink(){
  const params=new URLSearchParams(location.search);
  const code=(params.get('reservation')||'').trim().toUpperCase();
  const view=params.get('view')||'';
  if(!/^SC-\d{6}$/.test(code) && view!=='myReservations')return;
  if(typeof window.show==='function')window.show('myReservations');
  const ref=document.getElementById('findRef');
  if(ref&&/^SC-\d{6}$/.test(code))ref.value=code;
  await refreshRemoteMyReservations();
  if(/^SC-\d{6}$/.test(code)){
    const known=refs().some(x=>x.code===code);
    if(!known){
      const identity=document.getElementById('findIdentity');
      if(identity)identity.focus({preventScroll:true});
      const find=document.getElementById('findResult');
      if(find)find.innerHTML='<div class="smallnote">Reservation '+escapeHtml(code)+' is ready to open. Please verify with the room number, phone or e-mail used for the booking.</div>';
    }
  }
}
const oldShow=window.show;
window.show=function(id){oldShow(id);if(id==='myReservations')refreshRemoteMyReservations();if(id==='reserve')renderGuestTimes();};
document.addEventListener('DOMContentLoaded',()=>{refreshRemoteMyReservations();renderGuestTimes();handleReservationDeepLink();});
setTimeout(()=>{refreshRemoteMyReservations();renderGuestTimes();handleReservationDeepLink()},300);
})();