(function(){
const SB_URL='https://poxuyzcaejbqouelzwob.supabase.co';
const SB_KEY='sb_publishable_0Mo43IoJgWOu-7_Vps-BEw_e64ucHKI';
const GUEST_API=SB_URL+'/functions/v1/guest-reservations';
const sb=window.supabase.createClient(SB_URL,SB_KEY);
const TIMES=[];for(let h=17;h<=22;h++){for(const m of [0,15,30,45]){if(h===22&&m>0)continue;TIMES.push(String(h).padStart(2,'0')+':'+String(m).padStart(2,'0'))}}
const ACTIVE_FOR_TABLES=['pending','confirmed','reconfirmed','seated'];
const ACTIVE_FOR_CAPACITY=['confirmed','reconfirmed','seated'];
let rows=[],blocked=[],tables=[],assignments=[];
let assigningId=null;
let selectedTables=new Set();
const $=id=>document.getElementById(id);
function today(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function authMsg(t,ok=false){$('authMessage').textContent=t||'';$('authMessage').className='message '+(ok?'ok':'err')}
function row(r){return{id:Number(r.id),code:r.reservation_code,date:r.reservation_date,time:String(r.reservation_time||'').slice(0,5),guests:Number(r.party_size||0),name:r.lead_guest_name||'',room:r.room_number||'',phone:r.phone||'',email:r.email||'',request:r.special_request||'',status:r.status||'',staffNote:r.staff_note||''}}
function tableById(id){return tables.find(t=>Number(t.id)===Number(id))}
function bookingById(id){return rows.find(r=>Number(r.id)===Number(id))}
function assignmentIds(reservationId){return assignments.filter(a=>Number(a.reservation_id)===Number(reservationId)).map(a=>Number(a.table_id))}
function assignedTables(reservationId){return assignmentIds(reservationId).map(tableById).filter(Boolean)}
function assignedCodes(reservationId){const x=assignedTables(reservationId);return x.length?x.map(t=>t.table_code).join(' + '):'Not assigned'}
function assignedSeats(reservationId){return assignedTables(reservationId).reduce((n,t)=>n+Number(t.seats||0),0)}
function isBlocked(time){return blocked.some(x=>String(x.reservation_time||x.block_time||'').slice(0,5)===time)}
function currentServiceTime(){const d=new Date(),mins=d.getHours()*60+d.getMinutes();let best='17:00';for(const t of TIMES){const [h,m]=t.split(':').map(Number),v=h*60+m;if(v>=mins){best=t;break}best=t}return best}
async function apiGet(params){const u=new URL(GUEST_API);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,String(v)));const r=await fetch(u);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function staffSession(){const {data:{session}}=await sb.auth.getSession();if(!session)return null;const {data,error}=await sb.from('staff_profiles').select('*').eq('user_id',session.user.id).eq('active',true).maybeSingle();if(error||!data)return null;return {session,profile:data}}
async function refreshAuth(){const s=await staffSession();$('authCard').classList.toggle('hidden',!!s);$('dashboard').classList.toggle('hidden',!s);if(s){$('staffName').textContent=s.profile.full_name||s.session.user.email;await loadData()}return s}
async function login(){authMsg('Signing in...',true);const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){authMsg(error.message);return}const s=await staffSession();if(!s){await sb.auth.signOut();authMsg('This account is not an active Sushi Club staff account.');return}authMsg('');await refreshAuth()}
async function setup(){const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<8){authMsg('Enter the approved staff e-mail and a password of at least 8 characters.');return}authMsg('Creating staff account...',true);const {data,error}=await sb.auth.signUp({email,password});if(error){authMsg(error.message);return}if(data.session){const s=await staffSession();if(!s){await sb.auth.signOut();authMsg('Account created, but this e-mail is not approved for Sushi Club staff access.');return}authMsg('Staff account created.',true);await refreshAuth()}else authMsg('Account created. Please confirm the e-mail, then return here and sign in.',true)}
async function logout(){await sb.auth.signOut();$('dashboard').classList.add('hidden');$('authCard').classList.remove('hidden');authMsg('Signed out.',true)}
function populateTimeFilter(){const cur=$('timeFilter').value;$('timeFilter').innerHTML='<option value="all">All times</option>'+TIMES.map(t=>'<option value="'+t+'">'+t+'</option>').join('');if(cur&&[...TIMES,'all'].includes(cur))$('timeFilter').value=cur;else $('timeFilter').value='all'}
async function loadData(){const date=$('date').value||today();$('date').value=date;const [{data:rr,error:re},{data:bb,error:be},{data:tt,error:te}]=await Promise.all([
  sb.from('reservations').select('*').eq('reservation_date',date).order('reservation_time'),
  sb.from('blocked_slots').select('*').eq('active',true).or('reservation_date.eq.'+date+',block_date.eq.'+date),
  sb.from('restaurant_tables').select('*').eq('active',true).order('sort_order')
]);
if(re||be||te){alert((re||be||te).message);return}
rows=(rr||[]).map(row);blocked=bb||[];tables=tt||[];
const ids=rows.map(r=>r.id);assignments=[];
if(ids.length){const {data:aa,error:ae}=await sb.from('table_assignments').select('id,reservation_id,table_id,created_at').in('reservation_id',ids);if(ae){alert(ae.message);return}assignments=aa||[]}
renderAll()}
function renderAll(){renderStats();renderRequests();renderTables();renderSlots()}
function renderStats(){$('totalStat').textContent=rows.length;$('pendingStat').textContent=rows.filter(r=>r.status==='pending').length;$('confirmedStat').textContent=rows.filter(r=>['confirmed','reconfirmed'].includes(r.status)).length;$('paxStat').textContent=rows.filter(r=>ACTIVE_FOR_CAPACITY.includes(r.status)).reduce((n,r)=>n+r.guests,0)}
function filteredRows(){const st=$('status').value,time=$('timeFilter').value;return rows.filter(r=>(st==='all'||r.status===st)&&(time==='all'||r.time===time))}
function statusButtons(r){
  const table='<button onclick="window.staffOpenAssign('+r.id+')">TABLES</button>';
  if(r.status==='pending')return '<div class="actions three"><button class="primary" onclick="window.staffSetStatus('+r.id+',\'confirmed\')">CONFIRM</button><button class="danger" onclick="window.staffSetStatus('+r.id+',\'declined\')">DECLINE</button>'+table+'</div>';
  if(['confirmed','reconfirmed'].includes(r.status))return '<div class="actions three">'+table+'<button class="primary" onclick="window.staffSetStatus('+r.id+',\'seated\')">SEATED</button><button class="danger" onclick="window.staffSetStatus('+r.id+',\'no_show\')">NO-SHOW</button></div>';
  if(r.status==='seated')return '<div class="actions">'+table+'<button class="primary" onclick="window.staffSetStatus('+r.id+',\'completed\')">COMPLETE</button></div>';
  return ''
}
function renderRequests(){const shown=filteredRows();$('requests').innerHTML=shown.length?shown.map(r=>{
  const at=assignedTables(r.id),seat=assignedSeats(r.id);
  return '<div class="booking"><div class="top"><b>'+esc(r.time)+' · '+esc(r.name)+'</b><span class="pill '+esc(r.status)+'">'+esc(r.status)+'</span></div><div class="meta">'+r.guests+' guest(s)'+(r.room?' · Room '+esc(r.room):'')+(r.phone?' · '+esc(r.phone):'')+(r.email?' · '+esc(r.email):'')+(r.request?'<br>'+esc(r.request):'')+'<br>'+esc(r.code)+'</div><div class="assignment"><b>Table:</b> '+esc(assignedCodes(r.id))+(at.length?' · '+seat+' seats':'')+'</div>'+statusButtons(r)+'</div>'
}).join(''):'<p class="note">No reservations in this view.</p>'}
function occupantForTable(tableId,time,excludeId=null){for(const a of assignments){if(Number(a.table_id)!==Number(tableId))continue;const r=bookingById(a.reservation_id);if(!r||r.time!==time||!ACTIVE_FOR_TABLES.includes(r.status))continue;if(excludeId!==null&&Number(r.id)===Number(excludeId))continue;return r}return null}
function tableCard(t,time){if(!time||time==='all')return '<div class="table-card"><b>'+esc(t.table_code)+'</b><small>'+t.seats+' seats</small><small>Select a time</small></div>';const occ=occupantForTable(t.id,time);const blockedSlot=isBlocked(time);return '<div class="table-card '+(occ?'used':'free')+(blockedSlot?' blocked':'')+'"><b>'+esc(t.table_code)+'</b><small>'+t.seats+' seats</small><small>'+(blockedSlot?'Slot blocked':occ?esc(occ.name)+' · '+occ.guests+'p':'Available')+'</small></div>'}
function renderTables(){const time=$('timeFilter').value,inside=tables.filter(t=>t.area==='inside'),terrace=tables.filter(t=>t.area==='terrace');let html='';if(time==='all')html+='<p class="note" style="margin:0 0 12px">Choose a time above to see the live table plan.</p>';else if(isBlocked(time))html+='<p class="note" style="margin:0 0 12px">'+esc(time)+' is blocked for new reservations.</p>';html+='<div class="area-title">INSIDE</div><div class="table-grid">'+inside.map(t=>tableCard(t,time)).join('')+'</div><div class="area-title" style="margin-top:17px">TERRACE</div><div class="table-grid">'+terrace.map(t=>tableCard(t,time)).join('')+'</div>';$('tablesView').innerHTML=html}
function confirmedGuests(time){return rows.filter(r=>r.time===time&&ACTIVE_FOR_CAPACITY.includes(r.status)).reduce((n,r)=>n+r.guests,0)}
function usedTableCount(time){const set=new Set();for(const a of assignments){const r=bookingById(a.reservation_id);if(r&&r.time===time&&ACTIVE_FOR_CAPACITY.includes(r.status))set.add(Number(a.table_id))}return set.size}
function renderSlots(){const cap=tables.reduce((n,t)=>n+Number(t.seats||0),0);$('slots').innerHTML=TIMES.map(t=>'<div class="slot"><b>'+t+'</b><small>'+(isBlocked(t)?'Closed for new reservations':confirmedGuests(t)+' / '+cap+' confirmed guests · '+usedTableCount(t)+' tables assigned')+'</small><button class="'+(isBlocked(t)?'open':'')+'" onclick="window.staffToggleSlot(\''+t+'\')">'+(isBlocked(t)?'OPEN':'BLOCK')+'</button></div>').join('')}
async function addAudit(reservationId,action,oldStatus,newStatus,details){const s=await staffSession();if(!s)return;const {error}=await sb.from('reservation_audit').insert({reservation_id:reservationId,action,old_status:oldStatus||null,new_status:newStatus||null,actor_user_id:s.session.user.id,details:details||{}});if(error)console.warn(error.message)}
window.staffSetStatus=async function(id,status){const s=await staffSession();if(!s)return alert('Please sign in again.');const r=bookingById(id);if(!r)return;if(status==='confirmed'&&r.status==='pending'){const own=assignmentIds(r.id);if(own.length){if(assignedSeats(r.id)<r.guests)return alert('Assigned tables do not have enough seats for this reservation.');for(const tableId of own){const occ=occupantForTable(tableId,r.time,r.id);if(occ&&ACTIVE_FOR_CAPACITY.includes(occ.status))return alert('One of the assigned tables is already used by another confirmed reservation.')}}try{const j=await apiGet({action:'availability',date:r.date,party:r.guests});const slot=(j.slots||[]).find(x=>x.time===r.time);if(slot&&!slot.available)return alert('This time no longer has enough table capacity. Please choose another time or free a table first.')}catch(e){return alert('Availability could not be verified. Please try again.')}}const {error}=await sb.from('reservations').update({status}).eq('id',id);if(error)return alert(error.message);if(['declined','cancelled','completed','no_show'].includes(status)){const {error:de}=await sb.from('table_assignments').delete().eq('reservation_id',id);if(de)return alert(de.message)}await addAudit(id,'STAFF_STATUS',r.status,status,{});await loadData()}
window.staffToggleSlot=async function(time){const s=await staffSession();if(!s)return alert('Please sign in again.');const date=$('date').value,hit=blocked.find(x=>String(x.reservation_time||x.block_time||'').slice(0,5)===time);let error;if(hit)({error}=await sb.from('blocked_slots').delete().eq('id',hit.id));else({error}=await sb.from('blocked_slots').insert({reservation_date:date,reservation_time:time+':00',block_date:date,block_time:time+':00',active:true,created_by:s.session.user.id,reason:'Staff block'}));if(error)return alert(error.message);await loadData()}
function modalTableCard(t,r){const occ=occupantForTable(t.id,r.time,r.id),selected=selectedTables.has(Number(t.id)),disabled=!!occ;return '<button type="button" class="table-card selectable '+(selected?'selected ':'')+(disabled?'disabled':'')+'" '+(disabled?'disabled':'onclick="window.staffToggleTable('+Number(t.id)+')"')+'><b>'+esc(t.table_code)+'</b><small>'+t.seats+' seats</small><small>'+(occ?'Used by '+esc(occ.name):selected?'Selected':'Available')+'</small></button>'}
function renderAssignModal(){const r=bookingById(assigningId);if(!r)return;const inside=tables.filter(t=>t.area==='inside'),terrace=tables.filter(t=>t.area==='terrace'),selected=[...selectedTables].map(tableById).filter(Boolean),seat=selected.reduce((n,t)=>n+Number(t.seats||0),0);$('assignTitle').textContent=r.time+' · '+r.name;$('assignMeta').textContent=r.guests+' guest(s) · '+r.code;$('assignGrid').innerHTML='<div class="area-title">INSIDE</div><div class="table-grid">'+inside.map(t=>modalTableCard(t,r)).join('')+'</div><div class="area-title" style="margin-top:17px">TERRACE</div><div class="table-grid">'+terrace.map(t=>modalTableCard(t,r)).join('')+'</div>';$('assignSeatSummary').innerHTML='<b>'+seat+' seats selected</b> for '+r.guests+' guest(s)'+(seat>=r.guests?'<span class="ok"> · capacity OK</span>':'<span class="err"> · select more seats</span>')}
window.staffOpenAssign=function(id){const r=bookingById(id);if(!r)return;assigningId=r.id;selectedTables=new Set(assignmentIds(r.id));$('assignModal').classList.remove('hidden');renderAssignModal()}
window.staffToggleTable=function(tableId){if(selectedTables.has(Number(tableId)))selectedTables.delete(Number(tableId));else selectedTables.add(Number(tableId));renderAssignModal()}
function bestTables(r){const free=tables.filter(t=>!occupantForTable(t.id,r.time,r.id));let best=null;const n=free.length;for(let mask=1;mask<(1<<n);mask++){let seats=0,count=0,ids=[];for(let i=0;i<n;i++)if(mask&(1<<i)){seats+=Number(free[i].seats||0);count++;ids.push(Number(free[i].id))}if(seats<r.guests)continue;const waste=seats-r.guests;if(!best||waste<best.waste||(waste===best.waste&&count<best.count))best={ids,waste,count,seats};if(best&&best.waste===0&&best.count===1)break}return best}
function autoAssign(){const r=bookingById(assigningId);if(!r)return;const best=bestTables(r);if(!best)return alert('There is not enough free table capacity for this reservation.');selectedTables=new Set(best.ids);renderAssignModal()}
async function saveAssignment(){const s=await staffSession();if(!s)return alert('Please sign in again.');const r=bookingById(assigningId);if(!r)return;const chosen=[...selectedTables],seat=chosen.map(tableById).filter(Boolean).reduce((n,t)=>n+Number(t.seats||0),0);if(!chosen.length)return alert('Select at least one table, or use Clear Assignment.');if(seat<r.guests)return alert('Selected tables do not have enough seats for this reservation.');const {error}=await sb.rpc('sushi_staff_action',{p_id:r.id,p_action:'assign',p_table_ids:chosen,p_note:null});if(error)return alert(error.message);closeAssign();await loadData()}
async function clearAssignment(){const s=await staffSession();if(!s)return alert('Please sign in again.');const r=bookingById(assigningId);if(!r)return;const {error}=await sb.rpc('sushi_staff_action',{p_id:r.id,p_action:'clear',p_table_ids:null,p_note:null});if(error){if(error.message.includes('ONLY_PENDING_ASSIGNMENTS_CAN_BE_CLEARED'))return alert('Confirmed reservations must keep at least one table. Select replacement table(s) and press Save Tables instead.');return alert(error.message)}closeAssign();await loadData()}
async function addTable(){const s=await staffSession();if(!s)return alert('Please sign in again.');const code=$('newTableCode').value.trim().toUpperCase(),area=$('newTableArea').value,seats=Number($('newTableSeats').value);const msg=$('tableAdminMessage');msg.textContent='';msg.className='message';if(!/^[A-Z0-9-]{1,12}$/.test(code)){msg.textContent='Use a short table code such as I8 or T10.';msg.classList.add('err');return}if(!['inside','terrace'].includes(area)||!Number.isInteger(seats)||seats<1||seats>20){msg.textContent='Enter a valid area and seat count.';msg.classList.add('err');return}if(tables.some(t=>String(t.table_code).toUpperCase()===code)){msg.textContent='This table code already exists.';msg.classList.add('err');return}const sortOrder=(tables.reduce((m,t)=>Math.max(m,Number(t.sort_order)||0),0)||0)+10;const {error}=await sb.from('restaurant_tables').insert({table_code:code,area,seats,active:true,sort_order:sortOrder});if(error){msg.textContent=error.message;msg.classList.add('err');return}$('newTableCode').value='';$('newTableSeats').value='2';msg.textContent='Table added.';msg.classList.add('ok');await loadData()}
function closeAssign(){$('assignModal').classList.add('hidden');assigningId=null;selectedTables=new Set()}
function setTab(which){for(const [tab,card] of [['req','requestsCard'],['table','tablesCard'],['slot','slotsCard']]){$(tab+'Tab').classList.toggle('on',tab===which);$(card).classList.toggle('hidden',tab!==which)}if(which==='table'&&$('timeFilter').value==='all'){$('timeFilter').value=currentServiceTime();renderRequests();renderTables()}}
$('loginBtn').addEventListener('click',login);$('setupBtn').addEventListener('click',setup);$('logoutBtn').addEventListener('click',logout);$('date').value=today();populateTimeFilter();$('date').addEventListener('change',loadData);$('status').addEventListener('change',renderRequests);$('timeFilter').addEventListener('change',()=>{renderRequests();renderTables()});$('reqTab').addEventListener('click',()=>setTab('req'));$('tableTab').addEventListener('click',()=>setTab('table'));$('slotTab').addEventListener('click',()=>setTab('slot'));$('closeAssignBtn').addEventListener('click',closeAssign);$('assignModal').addEventListener('click',e=>{if(e.target===$('assignModal'))closeAssign()});$('autoAssignBtn').addEventListener('click',autoAssign);$('saveAssignBtn').addEventListener('click',saveAssignment);$('clearAssignBtn').addEventListener('click',clearAssignment);$('addTableBtn').addEventListener('click',addTable);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('assignModal').classList.contains('hidden'))closeAssign()});sb.auth.onAuthStateChange(()=>setTimeout(refreshAuth,0));refreshAuth();
})();